let suggestions = [
  "2Moons The Series",
  "Bad Buddy The Series",
  "Big Dragon  The Series",
  "HIStory 3 - Trapped",
  "KinnPorsche La Forte",
  "Love Tractor",
  "Manner of Death",
  "Semantic Error",
  "SOTUS The Series",
  "SOTUS S The Series",
  "TharnType The Series",
  "TharnType 2 - 7 Years of Love",
  "The Eclipse",
  "The Sign",
  "Together With Me",
  "Given",
  "2gether The Series",
  "Still 2gether",
  "Kieta Hatsukoi",
  "HIStory 2 - Crossing The Line",
  "To Be Continued",
  "The New Employee",
  "Cherry Magic - The Movie",
  "Just Friends",
  "Ai no Kotodama",
  "Boko mo Aitsu mo Shinrodesu",
  "Semantic Error - The Movie"
];
